#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri --http-status-ignore "403,302" --url-ignore "/tkdocs.com\/tutorial\/threads/,/pyinstaller.org\/en\/stable\/faq/,/learn.microsoft.com.*shell\/appdata/"
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-minimal.gemspec
