title: Jordan Schilling
author: Jordan Schilling
logo: /assets/img/logo.png
description: "View my SDLC journey. [github.com/jschilling12](https://github.com/jschilling12)"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
url: "https://jordanschilling.me"
baseurl: ""
future: true
